MODULE WignerCoupling
DESCRIPTION Wigner Coupling Support
VERSION 1.0
SOURCE Nathan Miller
BUILD_DATE JUN 2007
FUNCTION	WIGNER3J	6	6	KEYWORDS
FUNCTION	WIGNER6J	6	6 	KEYWORDS
#FUNCTION	WIGNER9J	2	2  KEYWORDS
FUNCTION	WIGNER3JVECT	4	4 KEYWORDS
#FUNCTION	WIGNER6JVECT	2	2  KEYWORDS
FUNCTION	CLEBSCHGORDON	6	6	KEYWORDS
FUNCTION	RACAHV		6	6	KEYWORDS
FUNCTION 	RACAHW		6	6	KEYWORDS
